name: Main

on:
- push
- pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Lint and test
      run: |
        bundle exec rake stree:check
        bundle exec rake
