name: Main

on:
- push
- pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0'
        bundler-cache: true
    - run: bundle exec rake stree:check
  versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
  test:
    needs: versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.versions.outputs.versions) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@master
    - if: matrix.ruby == 'head'
      run: rm Gemfile.lock
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test
